### ISSUE TITLE
How to run high-resolution data using Macruise

### ISSUE THREAD

**Issue by 11GaoMingshan** [MASILab/MaCRUISE#1]
Dear Author，

We have run MaCRUISE with high-resolution data, and when we running the step: Run MultiAlas skull strip , some problems occurred. We have checked the log file generated by it and the error is Java heap space. We know that this may be a problem with memory space. How to solve this problem?

Thanks

**Comment by saundersresearch** [comment]
I know this is an old issue, but thank you for bringing this up! We've applied MaCRUISE to higher resolution data using this Docker: [docker://masidocker/spiders:MaCRUISE_v3_1_0_BigMem](https://hub.docker.com/layers/masidocker/spiders/MaCRUISE_v3_1_0_BigMem/images/sha256-fb9b2ff9581b2cdb3a7421f390a5e0a9862c74816a93620adc586342307c6f90?context=explore).
